#!/usr/bin/env bash
# Reproducible on-device A/B harness for ARMX360 performance work.
#
# WHY THIS EXISTS. docs/gw-gpu-bottleneck-investigation.md section 10 lists eight
# methodology traps, and every one has already produced a WRONG conclusion at
# least once in this repo's history:
#
#   1. Cold pipeline cache reads 4-5fps low (a correct fix looked short).
#   2. An "A/B" between two configs that were never applied.
#   3. Per-game config files vanishing mid-session, silently reverting a setting.
#   4. SPIR-V opcode histograms mistaken for a cost model.
#   5. Generated bytecode headers surviving `git checkout` and silently linking
#      another commit's SPIR-V.
#   6. Counter selectors renumbered between driver generations.
#   7. ~+/-2fps run-to-run noise; a neutral commit was once reverted on it.
#   8. The driver is a free variable -- seven Turnip builds were installed on
#      the test device, and one run used a per-game driver override while the
#      global config named a different one.
#
# None of that is a discipline problem, it is a tooling problem: nothing forced
# the checks. This script makes them impossible to skip by turning each trap into
# an assertion that fails loudly, and by refusing to emit an fps number at all
# when the run is not trustworthy.
#
# WHERE THE GREP STRINGS COME FROM. Every pattern below was read out of the
# source, not guessed; each assertion cites its file:line. The short version:
#
#   "----------- CONFIG DUMP -----------" / "... END OF CONFIG DUMP ----"
#       config.cc:97 / config.cc:119 -- emitted by PrintConfigToLog() as ONE
#       XELOGI carrying embedded newlines, so only the FIRST physical line of
#       the dump carries a log prefix and the rest are bare.
#   "Loaded config: {}"                    config.cc:264
#   "Extracted title_id {:08X} from: {}"   config.cc:308
#   "Loading game config: {}"              config.cc:335
#   "  {} = {}"                            config.cc:350 (per applied override)
#   "Applied {} game config override(s)"   config.cc:354
#   "Loading custom Vulkan driver: {}"     ui/vulkan/vulkan_instance.cc
#   "Vulkan device '{}': API ..."           ui/vulkan/vulkan_device.cc
#   "* driverName: {}"                     ui/vulkan/vulkan_device.cc
#   "Shader storage: pipeline file ... (N bytes on disk)"  gpu/shader_storage.h:237
#   "Loaded N pipeline descriptions, M shader translations needed"
#                                          gpu/shader_storage.h:422
#
# THE LOG HAS NO FPS AND NO TIMESTAMP. xenia's file sink writes a prefix of
#   "<type>> f:<frame#:07> <thread id:08X> " (base/logging.cc) -- a guest frame
#   counter, not a clock. The overlay's fps lives in process-local atomics
#   (base/frame_stats.h) reachable only through JNI. So fps is sampled from the
#   compositor instead:
#     adb shell dumpsys SurfaceFlinger --latency '<layer>'
# whose rows are <desiredPresent> <actualPresent> <frameReady> in nanoseconds.
# The gap between consecutive actualPresent values is a true present-to-present
# interval, which is what this harness averages.
#
# USAGE: tools/bench-ab.sh <command> [options]   (--help for the list)
#
# Deliberately POSIX-ish bash with no exotic dependencies: this has to run on a
# dev's laptop over adb, not only in CI.
set -euo pipefail

PKG="${XENDROID_PKG:-armx360.compose}"
ADB="${ADB:-adb}"
SERIAL="${XENDROID_SERIAL:-}"

# Exit codes are meaningful so a wrapper can tell "the run failed" from
# "the run was correctly rejected".
EX_OK=0         # ran, all assertions held
EX_FAIL=1       # an assertion failed -- the measurement is void
EX_USAGE=2      # bad invocation
EX_UNTRUSTED=3  # refused to report (instrumented driver, cold cache, too few samples)

RED=''; YEL=''; GRN=''; BLD=''; RST=''
if [ -t 1 ]; then RED=$'\033[31m'; YEL=$'\033[33m'; GRN=$'\033[32m'; BLD=$'\033[1m'; RST=$'\033[0m'; fi

die()  { printf '%sbench-ab: %s%s\n' "$RED" "$1" "$RST" >&2; exit "${2:-$EX_FAIL}"; }
warn() { printf '%sbench-ab: WARNING: %s%s\n' "$YEL" "$*" "$RST" >&2; }
info() { printf '%s%s%s\n' "$BLD" "$*" "$RST" >&2; }

usage() {
  cat <<'EOF'
tools/bench-ab.sh -- reproducible on-device A/B harness

  preflight        Host checks that must pass BEFORE building or running: stale
                   generated SPIR-V bytecode, missing host tools, dirty tree.
  device-info      Record device/GPU/driver identity + the per-game config
                   inventory. Run per device and diff it between arms.
  snapshot-config  Record the per-game config file's identity (size + sha256)
                   BEFORE a run. Fails if the file is missing.
  verify-config    Re-check that file AFTER a run; fail if it vanished or changed.
  wait-layer       Block until the emulator's SurfaceFlinger layer appears and
                   print its name (needed by `sample`).
  sample           Sample present-to-present fps for N seconds; append a CSV row.
  assert-log       OFFLINE. Apply every xe.log assertion to a log FILE.
  report           Aggregate samples; refuse to report fps on an instrumented
                   driver or from a cold-cache run.
  compare          Compare two reports; verdict is "within noise" unless the
                   delta exceeds 2 standard errors.

Common options:
  --title-id ID     8-hex title id, e.g. 584108FF.
  --log FILE        Local xe.log copy (assert-log / report).
  --driver-path P   vulkan_lib_path the run is REQUIRED to have applied.
  --expect SPEC     game.NAME=VALUE | global.NAME=VALUE (assert-log), repeatable.
                    game.*   -> the per-game override block (config.cc:350).
                               Strong: only keys present in the file AND matching
                               a registered cvar get a line.
                    global.* -> the global CONFIG DUMP (config.cc:97/119).
                               Weaker: reflects the file text, not the live cvar.
                    Omit =VALUE to assert only that the key was applied.
  --samples N       Samples to take. Default 3.
  --seconds N       Seconds per sample (sample). Default 20.
  --out FILE        Output path for the CSV this command writes.
  --label NAME      Arm name, used in samples.csv and reports.
  --min-samples N   Refuse to report below this many samples. Default 3.

Environment:
  XENDROID_PKG      Package name. Default armx360.compose (the release id).
                    Use armx360.compose.debug for the debuggable variant.
  XENDROID_SERIAL   Device serial (required when more than one is attached).
EOF
}

# ---------------------------------------------------------------- adb plumbing

adb_do() { if [ -n "$SERIAL" ]; then "$ADB" -s "$SERIAL" "$@"; else "$ADB" "$@"; fi; }

# Resolve the single attached device. Refusing to guess is deliberate: attaching
# two devices is a classic way to measure the wrong phone.
require_device() {
  [ -n "$SERIAL" ] && return 0
  local n
  n="$(adb_do devices 2>/dev/null | awk 'NR>1 && $2=="device"{c++} END{print c+0}')"
  [ "${n:-0}" -ge 1 ] || die "no device in 'adb devices'" "$EX_USAGE"
  [ "$n" -eq 1 ] || die "$n devices attached; set XENDROID_SERIAL to choose" "$EX_USAGE"
}

# adb shell word-splits and chokes on parentheses unless the whole remote command
# arrives as ONE quoted argument; and every device speaks CRLF. Hence the wrapper.
sh() { adb_do shell "$*" 2>/dev/null | tr -d '\r'; }

device_dir() { printf '/sdcard/Android/data/%s/files/compose' "$PKG"; }
game_config_path() { printf '%s/config/%s.config.toml' "$(device_dir)" "$1"; }

# ---------------------------------------------------------------- log parsing

# xenia's file sink prefixes each *record* with "<type>> f:<frame> <thread> ".
# A record may carry embedded newlines (the CONFIG DUMP does), so stripping the
# prefix from EVERY physical line -- not just the first -- is what makes that
# dump greppable at all.
strip_prefix() { sed -E 's/^[!widx]?> f:[0-9]{7} [0-9A-F]{8} //'; }

# The normalised view every assertion runs against: prefixes removed, CR gone.
normalise_log() { strip_prefix <"$1" >"$2"; }

# Accumulate every failure instead of exiting on the first, so one pass reports
# all the ways in which a run is untrustworthy rather than only the first.
FAILED=0
fail() { printf '  %sFAIL%s %s\n' "$RED" "$RST" "$*"; FAILED=$((FAILED + 1)); }
pass() { printf '  %sok%s   %s\n' "$GRN" "$RST" "$*"; }

# Normalise a TOML scalar for comparison. toml++ streams string values back out
# quoted and single-quoted TOML literals keep their quotes, so comparison has to
# be quote-insensitive or every string cvar would "fail" spuriously.
canon() { printf '%s' "$1" | sed -E "s/^[[:space:]]+//; s/[[:space:]]+$//; s/^['\"]//; s/['\"]$//"; }

# =============================================================== xe.log asserts
#
# All of these take the NORMALISED log (prefixes already stripped) so that the
# CONFIG DUMP's continuation lines are visible to grep.

# Body of the CONFIG DUMP: everything strictly between the "----------- CONFIG
# DUMP -----------" marker (config.cc:97) and the "----------- END OF CONFIG DUMP
# ----" marker (config.cc:119). Returns non-zero if the markers are absent --
# which is itself a finding: on Android the dump is printed from ReadConfig(), so
# a missing dump means the global config was never read and NO global cvar can
# be trusted.
config_dump_body() {
  awk '
    /^-{11} CONFIG DUMP -{11}$/ { inb=1; next }
    inb && /^-{11} END OF CONFIG DUMP -{4}$/ { exit }
    inb { print }
  ' "$1"
}

has_config_dump() { grep -q 'CONFIG DUMP' "$1"; }

# The per-game block: config.cc:335 logs "Loading game config: <path>", then one
# "  <name> = <value>" line per key actually applied (config.cc:350), then
# "Applied N game config override(s)" (config.cc:354). Take only the lines
# BETWEEN the first and last, so the count line is never mistaken for a key.
game_config_block() {
  awk '
    /^Loading game config: / { inb=1; next }
    inb && /^Applied [0-9]+ game config override\(s\)/ { inb=0 }
    inb { print }
  ' "$1"
}

# How many overrides did the run claim? Echoes N, or nothing.
game_override_count() {
  sed -nE 's/^Applied ([0-9]+) game config override\(s\)$/\1/p' "$1" | tail -1
}

# Did the run even LOOK at a per-game config? config.cc:329-331 returns early
# with NO log line at all when the file does not exist, so the ABSENCE of
# "Loading game config:" is the machine-readable signature of "no per-game
# config was applied" -- exactly trap 3.
game_config_path_logged() {
  sed -nE 's/^Loading game config: (.*)$/\1/p' "$1" | tail -1
}

# assert_cvar_game <normlog> <name> <expected-value>
#
# Asserts one cvar was applied FROM THE PER-GAME CONFIG, with the given value.
#
# Why this shape: config.cc:350 prints config_var->name() -- the BARE name, not
# "category.name". So the category cannot be checked from this line; the caller
# checks it against the on-device TOML instead. Matching on the bare name here
# is still far stronger than matching nothing, because this line exists ONLY for
# keys that were present in the file AND matched a registered cvar.
#
# A missing key fails LOUDLY. Two published "results" in this project were
# configs that had never actually changed, so an unapplied cvar must never be a
# silent pass.
assert_cvar_game() {
  local log="$1" name="$2" want="$3" block got
  block="$(game_config_block "$log")"
  if [ -z "$block" ]; then
    fail "cvar '$name': no per-game config was applied at all (no 'Loading game config:' line)"
    return 1
  fi
  got="$(printf '%s\n' "$block" | sed -nE "s/^  ${name} = (.*)$/\1/p" | tail -1)"
  if [ -z "$got" ]; then
    fail "cvar '$name': NOT applied (absent from the per-game override block)"
    return 1
  fi
  if [ -n "$want" ] && [ "$(canon "$got")" != "$(canon "$want")" ]; then
    fail "cvar '$name': applied as '$(canon "$got")' but the run intended '$(canon "$want")'"
    return 1
  fi
  pass "cvar '$name' = $(canon "$got") (applied via per-game config)"
}

# assert_cvar_global <normlog> <name> <expected-value>
#
# Asserts a cvar was present in the GLOBAL config, as evidenced by the CONFIG
# DUMP. Weaker than assert_cvar_game: the dump reflects the file's text, not the
# live cvar, so a later per-game override could still win. Use it for the
# device/driver-level cvars you set globally (vulkan_lib_path, turnip_debug),
# and prefer assert_cvar_game for anything under test.
assert_cvar_global() {
  local log="$1" name="$2" want="$3" got
  if ! has_config_dump "$log"; then
    fail "cvar '$name': no CONFIG DUMP in the log -- the global config was never read"
    return 1
  fi
  got="$(config_dump_body "$log" | sed -nE "s/^[[:space:]]*${name} = (.*)$/\1/p" | tail -1)"
  if [ -z "$got" ]; then
    fail "cvar '$name': NOT present in the global CONFIG DUMP"
    return 1
  fi
  if [ -n "$want" ] && [ "$(canon "$got")" != "$(canon "$want")" ]; then
    fail "cvar '$name': global config has '$(canon "$got")' but the run intended '$(canon "$want")'"
    return 1
  fi
  pass "cvar '$name' = $(canon "$got") (present in global CONFIG DUMP)"
}

# =========================================================== driver assertions
#
# Trap 8: seven Turnip builds were installed on one test device and at least one
# run used a per-game vulkan_lib_path override while the global config named a
# different one. So the driver is RECORDED on every run and, when the caller
# knows what it must be, PINNED.

# Which driver library did this run actually load?
#   "Loading custom Vulkan driver: <path>"   ui/vulkan/vulkan_instance.cc
# A per-game vulkan_lib_path and a global one produce the SAME line, so this
# reports what ran -- which is the thing that has to match across arms.
driver_path_logged() {
  sed -nE 's/^Loading custom Vulkan driver: (.*)$/\1/p' "$1" | tail -1
}
# Fallback identity when no custom driver was loaded: the system ICD. We take the
# "Vulkan device '<name>':" line (ui/vulkan/vulkan_device.cc) and, when the
# driver exposes VK_KHR_driver_properties, its "* driverName:" line -- the
# strongest available identification of what actually ran.
vulkan_device_line() { sed -nE "s/^Vulkan device '([^']*)'.*/\1/p" "$1" | head -1; }
driver_name_line()  { sed -nE 's/^\* driverName: (.*)$/\1/p' "$1" | tail -1; }

# TU_DEBUG / TU_PERF_SAMPLER are logged by vulkan_instance.cc when the matching
# cvars are non-empty, so their presence proves those cvars applied too.
tu_debug_logged()        { sed -nE 's/^Set TU_DEBUG=(.*) for the Turnip Vulkan driver$/\1/p' "$1" | tail -1; }
tu_perf_sampler_logged() { sed -nE 's/^Set TU_PERF_SAMPLER=(.*) for the Turnip driver$/\1/p' "$1" | tail -1; }

# Is this the INSTRUMENTED Turnip build (the one carrying the KGSL counter
# sampler)? It sets TU_PERF_SAMPLER. docs/gw-gpu-bottleneck-investigation.md
# sections 3 and 12.5 are explicit that instrumented runs are for LOCATING
# bottlenecks and NEVER for fps claims: the sampler reserves ~100 hardware
# counters and polls them from a background thread.
is_instrumented() { [ -n "$(tu_perf_sampler_logged "$1")" ]; }

# assert_driver <normlog> [required-path]
# Records the driver always; pins it when required-path is given.
assert_driver() {
  local log="$1" want="${2:-}" path name dev
  path="$(driver_path_logged "$log")"
  name="$(driver_name_line "$log")"
  dev="$(vulkan_device_line "$log")"
  [ -n "$dev" ] || fail "no 'Vulkan device' line in the log -- cannot identify the GPU at all"
  printf 'driver.lib=%s\n' "${path:-<system>}"
  printf 'driver.name=%s\n' "${name:-<unreported>}"
  printf 'gpu.device=%s\n' "${dev:-<unknown>}"
  if [ -n "$want" ]; then
    # Match on the tail so a caller may pass the full path or just the
    # distinctive build directory (e.g. "a6xx-instrumented-perf").
    case "$path" in
      *"$want"*) pass "driver pinned: loaded '$path'" ;;
      *) fail "driver mismatch: intended '*$want' but the log shows '${path:-<system driver>}'" ;;
    esac
  else
    pass "driver recorded: ${path:-<system>} / ${name:-<name unreported>}"
  fi
  # A configured path that does not exist falls back to the SYSTEM driver with
  # only a warning (vulkan_instance.cc). That is precisely how a run ends up on
  # a different driver than intended while looking healthy, so it is a hard fail.
  if grep -q 'was set but the file does not exist' "$log"; then
    fail "a configured custom driver path did not exist; the run fell back to the SYSTEM driver"
  fi
}

# ====================================================== pipeline-cache asserts
#
# Trap 1: store_shaders persists a per-title pipeline cache; the FIRST run after
# a new build recompiles pipelines during gameplay and reads several fps low. A
# correct shader fix once looked 4-5fps short purely from this.
#
# The log makes this DETECTABLE instead of a matter of memory
# (gpu/shader_storage.h):
#   "Shader storage: pipeline file <path> (N bytes on disk)"      :237
#   "Loaded N shaders from storage"                               :411
#   "Loaded N pipeline descriptions, M shader translations needed" :422
# A warm cache reports a non-zero on-disk size. Zero bytes -- or a missing line
# with store_shaders on -- means this run paid the compile cost and MUST be
# discarded.

pipeline_cache_bytes() {
  sed -nE 's/^Shader storage: pipeline file .* \(([0-9]+) bytes on disk\)$/\1/p' "$1" | tail -1
}
shaders_from_storage() { sed -nE 's/^Loaded ([0-9]+) shaders from storage$/\1/p' "$1" | tail -1; }
translations_needed() {
  sed -nE 's/^Loaded [0-9]+ pipeline descriptions, ([0-9]+) shader translations needed$/\1/p' "$1" | tail -1
}

# assert_cache_warm <normlog>  -- returns 0 when warm, 1 when it must be discarded.
assert_cache_warm() {
  local log="$1" bytes
  bytes="$(pipeline_cache_bytes "$log")"
  if [ -z "$bytes" ]; then
    warn "no 'Shader storage: pipeline file' line -- cannot PROVE the cache was warm."
    warn "  Expected when store_shaders is off; otherwise this run must be DISCARDED."
    return 1
  fi
  printf 'cache.bytes=%s\n' "$bytes"
  printf 'cache.shaders_from_storage=%s\n' "$(shaders_from_storage "$log" || echo '?')"
  printf 'cache.translations_needed=%s\n' "$(translations_needed "$log" || echo '?')"
  if [ "$bytes" -gt 0 ]; then
    pass "pipeline cache was warm (${bytes} bytes on disk)"
    return 0
  fi
  fail "pipeline cache was COLD (0 bytes on disk) -- this run must be DISCARDED"
  return 1
}

# ==================================================================== commands

# ---- preflight -------------------------------------------------------------
#
# Trap 5: the generated SPIR-V bytecode headers are git-IGNORED
# (.gitignore:86-89 lists gpu/shaders/bytecode/vulkan_spirv/) and are regenerated
# only when the OUTPUT IS OLDER THAN ITS SOURCE (gen_android_spirv.py:165,
# `os.path.getmtime(out) >= os.path.getmtime(src)` -> skip). `git checkout`
# updates source mtimes but leaves generated headers alone, and checking out an
# OLDER commit can leave headers NEWER than their sources -- so the incremental
# check happily skips and the build links another commit's SPIR-V. One commit in
# this project (465a6e121) is permanently untestable for exactly this reason.
cmd_preflight() {
  local repo shaders bytecode gen newest stale=0
  repo="$(git rev-parse --show-toplevel 2>/dev/null)" || die "not inside a git worktree"
  shaders="$repo/emulator-core/src/main/cpp/xenia/src/xenia/gpu/shaders"
  bytecode="$shaders/bytecode/vulkan_spirv"
  gen="$repo/emulator-core/src/main/cpp/xenia/tools/build/gen_android_spirv.py"

  info "repo: $repo"
  printf 'git.commit=%s\n' "$(git -C "$repo" rev-parse --short HEAD)"

  # The host toolchain the generator needs. Its absence means bytecode CANNOT be
  # regenerated, so whatever headers exist are untrustworthy.
  local missing=() t
  for t in python3 glslangValidator spirv-opt spirv-dis; do
    command -v "$t" >/dev/null 2>&1 || missing+=("$t")
  done
  if [ "${#missing[@]}" -gt 0 ]; then
    printf 'preflight.missing_tools=%s\n' "${missing[*]}"
    warn "missing host tools: ${missing[*]} -- bytecode cannot be regenerated."
    warn "  If bytecode exists it may be STALE (trap 5). Wipe it or install the tools."
  else
    pass "host shader toolchain present"
  fi

  if [ -d "$bytecode" ]; then
    local n; n="$(find "$bytecode" -name '*.h' | wc -l | tr -d ' ')"
    printf 'preflight.bytecode_headers=%s\n' "$n"
    # The same newest-source rule the generator applies, evaluated over the dir.
    newest="$(find "$shaders" -maxdepth 1 \
      \( -name '*.slang' -o -name '*.glsl' -o -name '*.xesl' -o -name '*.xesli' \) \
      -newer "$bytecode" -print -quit 2>/dev/null || true)"
    if [ -n "$newest" ]; then
      stale=1
      warn "STALE BYTECODE: $(basename "$newest") is newer than the bytecode dir."
      warn "  The generator would skip it (mtime >= source) and link old SPIR-V."
      warn "  Fix: rm -rf '$bytecode' and rebuild."
    else
      pass "no shader source newer than the generated bytecode"
    fi
    if [ -f "$gen" ] && [ "${#missing[@]}" -eq 0 ]; then
      # Ask the generator itself. It ends with
      # "N generated, M up-to-date, F skipped/failed"; F>0 means shaders that
      # failed to compile, i.e. the build would link a partial shader set.
      local out
      if ! out="$(python3 "$gen" --strict "$shaders" 2>&1)"; then
        warn "bytecode generator reported failure:"
        printf '%s\n' "$out" | sed 's/^/    /' >&2
        stale=1
      fi
      printf '%s\n' "$out" | sed -nE 's/^spirv bytecode: /preflight.bytecode: /p' >&2
      printf '%s\n' "$out" | grep -qE 'skipped/failed' || stale=1
    fi
  else
    printf 'preflight.bytecode_headers=0\n'
    info "no bytecode dir yet (the first build generates it)"
  fi

  local dirty; dirty="$(git -C "$repo" status --porcelain | wc -l | tr -d ' ')"
  printf 'git.dirty_entries=%s\n' "$dirty"
  [ "$dirty" -eq 0 ] || warn "working tree has $dirty modified/untracked entries -- record which."

  [ "$stale" -eq 0 ] || exit "$EX_FAIL"
  return 0
}

# ---- device-info -----------------------------------------------------------
#
# Records the free variables (trap 8) so two arms can be diffed. Driver identity
# is the one that has bitten this project hardest.
cmd_device_info() {
  require_device
  # Default to stdout. `tee /dev/stdout` is NOT portable here: on many Android
  # shells /dev/stdout is not a writable device node, which turned this command
  # into a spurious failure. Write to a temp file and cat it instead.
  local out="${1:-}" tmp; tmp="$(mktemp)"
  local dir; dir="$(device_dir)"
  {
    printf 'device.serial=%s\n' "$(adb_do get-serialno 2>/dev/null | tr -d '\r')"
    printf 'device.model=%s\n' "$(sh getprop ro.product.model)"
    printf 'device.android=%s\n' "$(sh getprop ro.build.version.release)"
    printf 'device.abi=%s\n' "$(sh getprop ro.product.cpu.abi)"
    printf 'device.soc=%s\n' "$(sh getprop ro.hardware)"
    printf 'package=%s\n' "$PKG"
    printf 'storage.dir=%s\n' "$dir"
    printf 'config_dir_entries=%s\n' "$(sh ls "$dir/config" 2>/dev/null | tr '\n' ' ')"
    printf 'driver_dir=%s\n' "$(sh ls "$dir/driver" 2>/dev/null | tr '\n' ' ')"
  } >"$tmp"
  if [ -n "$out" ]; then cp "$tmp" "$out"; cat "$tmp"; else cat "$tmp"; fi
  rm -f "$tmp"
  info "per-game configs present:"
  sh ls -l "$dir/config" 2>/dev/null | sed 's/^/  /' >&2 \
    || warn "no config dir at $dir/config (every per-game override would be a no-op)"
  return 0
}

# ---- per-game config presence (trap 3) -------------------------------------
#
# Trap 3 in its exact form: "GW's config was deleted mid-session, silently
# reverting readback_resolve from none to the global uma -- which looked like a
# broken build." So record the file's identity BEFORE the run and re-check it
# AFTER. Size + sha256 catches a rewrite as well as a delete.
#
# The real path: GetGameConfigPath() (config.cc:50) builds
# <config_folder>/config/<TITLEID>.config.toml, where config_folder is the
# --storage_root the app passes (EmulatorHostActivity.kt ->
# Utils.get_storage_root_path() -> Application.get_app_data_dir()), i.e.
# /sdcard/Android/data/<pkg>/files/compose on this fork.
snapshot_config() {
  local title="$1" path size sum
  path="$(game_config_path "$title")"
  size="$(sh stat -c '%s' "$path" 2>/dev/null || true)"
  [ -n "$size" ] || die "per-game config NOT FOUND: $path
  (trap 3: it must exist before the run, otherwise every 'override' is a no-op)" "$EX_FAIL"
  sum="$(sh sha256sum "$path" 2>/dev/null | cut -d' ' -f1)"
  [ -n "$sum" ] || die "cannot hash $path" "$EX_FAIL"
  printf '%s %s %s\n' "$title" "$size" "$sum"
}

cmd_snapshot_config() {
  require_device
  [ -n "$TITLE_ID" ] || die "--title-id required"
  local snap; snap="$(snapshot_config "$TITLE_ID")"
  printf 'before %s\n' "$snap"
  [ -n "$OUT" ] && printf '%s\n' "$snap" >"$OUT"
  return 0
}

cmd_verify_config() {
  require_device
  [ -n "$TITLE_ID" ] || die "--title-id required"
  local after asum bsum
  after="$(snapshot_config "$TITLE_ID")"
  printf 'after  %s\n' "$after"
  asum="$(printf '%s' "$after" | awk '{print $3}')"
  [ -n "$asum" ] || die "could not re-hash the per-game config" "$EX_FAIL"
  bsum="$BEFORE_SUM"
  if [ -z "$bsum" ]; then
    warn "no --before sha256 supplied; cannot detect a mid-run change"
    return 0
  fi
  if [ "$bsum" != "$asum" ]; then
    die "per-game config CHANGED during the run (trap 3).
  before sha256=$bsum
  after  sha256=$asum
  A setting may have been silently reverted; this measurement is void." "$EX_FAIL"
  fi
  pass "per-game config unchanged across the run (sha256=$asum)"
}

# ---- fps sampling ----------------------------------------------------------
#
# `dumpsys SurfaceFlinger --latency <layer>` rows are
#   <desiredPresent> <actualPresent> <frameReady>   (nanoseconds)
# with the display refresh period on line 1. We average the actualPresent deltas.
# The FIRST interval is dropped: it spans from layer creation, not a steady frame.
find_layer() {
  sh dumpsys SurfaceFlinger --list 2>/dev/null \
    | grep -F "$1" | grep -E '^SurfaceView\[' | sed 's/#[0-9]*$//' | head -1
}

cmd_wait_layer() {
  require_device
  local i=0 layer=""
  while [ "$i" -lt "${TIMEOUT:-120}" ]; do
    layer="$(find_layer "$PKG")"
    [ -n "$layer" ] && { printf '%s\n' "$layer"; return 0; }
    sleep 1; i=$((i + 1))
  done
  die "no SurfaceView layer for $PKG after ${TIMEOUT:-120}s -- is the game running?" "$EX_USAGE"
}

# latency_fps <layer> -> "<mean_ms> <fps> <n_intervals>"
latency_fps() {
  sh dumpsys SurfaceFlinger --latency "'$1'" 2>/dev/null | awk '
    NR > 1 && $2 > 0 { t[n++] = $2 }
    END {
      if (n < 3) exit 1
      sum = 0; cnt = 0
      for (i = 1; i < n - 1; i++) {
        d = (t[i+1] - t[i]) / 1e6
        if (d > 0 && d < 1000) { sum += d; cnt++ }   # drop stalls/pauses
      }
      if (cnt == 0) exit 1
      mean = sum / cnt
      printf "%.4f %.3f %d\n", mean, 1000.0 / mean, cnt
    }'
}

cmd_sample() {
  require_device
  local layer out seconds samples
  layer="${LAYER:-$(cmd_wait_layer)}"
  seconds="$SECONDS_PER_SAMPLE"; samples="$SAMPLES"; out="${OUT:-samples.csv}"
  [ -f "$out" ] || printf 'label,mean_ms,fps,n_intervals\n' >"$out"
  info "layer: $layer"
  info "taking $samples sample(s) of ${seconds}s"
  local i=1 ms fps n
  while [ "$i" -le "$samples" ]; do
    sleep "$seconds"
    if ! read -r ms fps n <<<"$(latency_fps "$layer")"; then
      warn "sample $i: no usable present timestamps (is the game rendering?)"
      i=$((i + 1)); continue
    fi
    printf '%s,%s,%s,%s\n' "$LABEL" "$ms" "$fps" "$n" | tee -a "$out"
    i=$((i + 1))
  done
  return 0
}

# ---- assert-log (OFFLINE; the unit-tested core) ---------------------------
#
# Applies every xe.log assertion to a LOCAL log file. No device required, which
# is what makes this testable: tools/bench-ab-test.sh drives it with fixtures
# that are deliberately missing a cvar and REQUIRES it to fail.
#
# Each --expect declares WHERE the value is supposed to have come from, because
# the two sources prove different things:
#
#   game.NAME=VALUE     the per-game override block (config.cc:350). Strong: the
#                       line only exists for a key that was in the file AND
#                       matched a registered cvar. This is the per-game config
#                       path from GetGameConfigPath() (config.cc:50).
#   global.NAME=VALUE   the global CONFIG DUMP (config.cc:97/119). Weaker: it
#                       reflects the file's TEXT, not the live cvar, so a later
#                       per-game override could still win. Use for the
#                       device/driver-level cvars set globally.
#
# Omitting the expected value asserts only that the key was applied at all.
cmd_assert_log() {
  [ -n "$LOG" ] || die "--log required" "$EX_USAGE"
  [ -f "$LOG" ] || die "no such log: $LOG" "$EX_USAGE"
  local norm; norm="$(mktemp)"
  normalise_log "$LOG" "$norm"

  printf 'log.bytes=%s\n' "$(wc -c <"$LOG" | tr -d ' ')"
  printf 'log.game_overrides=%s\n' "$(game_override_count "$norm" || echo 0)"
  printf 'log.game_config=%s\n' "$(game_config_path_logged "$norm" || echo '<none>')"
  printf 'log.instrumented=%s\n' "$(is_instrumented "$norm" && echo yes || echo no)"

  local spec name val
  for spec in ${CVARS[@]+"${CVARS[@]}"}; do
    name="${spec%%=*}"; val=""
    case "$spec" in *=*) val="${spec#*=}";; esac
    case "$name" in
      game.*)   name="${name#game.}";   assert_cvar_game   "$norm" "$name" "$val";;
      global.*) name="${name#global.}"; assert_cvar_global "$norm" "$name" "$val";;
      # An unqualified name is a usage error rather than a guess: silently
      # checking the wrong source is exactly how a "config applied" claim goes
      # wrong in the first place.
      *) fail "bad --expect '$name': qualify it as game.NAME or global.NAME"
         continue;;
    esac
  done

  assert_driver "$norm" "$DRIVER_PATH"
  # Cache state is reported, and a cold cache FAILS, but it must not mask the
  # per-cvar findings above -- so its non-zero return is tolerated here.
  assert_cache_warm "$norm" || true

  rm -f "$norm"
  printf 'assert.failures=%d\n' "$FAILED"
  [ "$FAILED" -eq 0 ] || exit "$EX_FAIL"
  return 0
}

# ---- report ---------------------------------------------------------------
#
# Aggregates a samples CSV and refuses to report fps when the number would be
# meaningless:
#   * an INSTRUMENTED driver build (locating bottlenecks only, never fps claims)
#   * a cold pipeline cache (trap 1)
#   * fewer than MIN_SAMPLES samples (noise is unquantifiable from one point)
cmd_report() {
  local csv="${1:-}" label="$LABEL"
  [ -n "$csv" ] || csv="samples.csv"
  [ -f "$csv" ] || die "no samples file: $csv" "$EX_USAGE"
  # Header: label,mean_ms,fps,n_intervals
  awk -F, -v l="$label" 'NR>1 && $1==l && $3>0 { n++; s += $3; ss += $3*$3 } END {
    if (n == 0) { print "no samples for label " l > "/dev/stderr"; exit 1 }
    m = s/n
    # Sample standard deviation. With one sample it is 0 -- which is exactly why
    # we require MIN_SAMPLES: a single reading has no noise estimate at all.
    sd = (n > 1) ? sqrt((ss - n*m*m) / (n-1)) : 0
    printf "label=%s\nsamples=%d\nfps_mean=%.3f\nfps_sd=%.3f\n", l, n, m, sd
  }' "$csv" >"$csv.report" || die "report failed for '$label'" "$EX_FAIL"
  cat "$csv.report"

  if [ -n "$LOG" ] && [ -f "$LOG" ]; then
    local norm; norm="$(mktemp)"
    normalise_log "$LOG" "$norm"
    if is_instrumented "$norm"; then
      rm -f "$norm"
      die "REFUSING to report fps: this run used the INSTRUMENTED Turnip build.
  It reserves ~100 hardware counters and polls them from a background thread, so
  its fps is not comparable with a production-driver run.
  docs/gw-gpu-bottleneck-investigation.md sections 3 / 12.5: instrumented runs
  are for LOCATING bottlenecks, never for fps claims." "$EX_UNTRUSTED"
    fi
    if ! assert_cache_warm "$norm" >/dev/null 2>&1; then
      rm -f "$norm"
      die "REFUSING to report fps: the pipeline cache was cold (trap 1).
  Re-run and take the SECOND run; a cold-cache reading is several fps low." "$EX_UNTRUSTED"
    fi
    rm -f "$norm"
  else
    warn "no --log given: the instrumented-driver and cold-cache gates were NOT applied"
  fi

  local n; n="$(sed -nE 's/^samples=([0-9]+)$/\1/p' "$csv.report")"
  if [ "${n:-0}" -lt "$MIN_SAMPLES" ]; then
    die "REFUSING to report: only ${n:-0} sample(s); need >= $MIN_SAMPLES to estimate noise." "$EX_UNTRUSTED"
  fi
  return 0
}

# ---- compare ---------------------------------------------------------------
#
# Trap 7: device readings carry ~+/-2fps, and a neutral commit was once REVERTED
# on the strength of a 13-vs-15 reading. So a delta is only called real when it
# exceeds 2 standard errors of the difference; anything smaller is reported as
# noise, explicitly, instead of being left for the reader to eyeball.
#
#   se = sqrt(sd_a^2/n_a + sd_b^2/n_b)
# With n=3 per arm and sd~2fps that is a ~+/-2.7fps band -- deliberately
# conservative, because under-reading a real win costs less than inventing one.
cmd_compare() {
  local a="${1:-}" b="${2:-}"
  [ -n "$a" ] && [ -n "$b" ] || die "compare needs two report files" "$EX_USAGE"
  [ -f "$a" ] || die "no report: $a" "$EX_USAGE"
  [ -f "$b" ] || die "no report: $b" "$EX_USAGE"
  set +e
  awk -F= '
    FNR==NR { if ($1 ~ /^(label|fps_mean|fps_sd|samples)$/) A[$1]=$2; next }
    { if ($1 ~ /^(label|fps_mean|fps_sd|samples)$/) B[$1]=$2 }
    END {
      if (!(("fps_mean" in A) && ("fps_mean" in B))) {
        print "malformed report file (no fps_mean key)" > "/dev/stderr"; exit 2
      }
      if (A["samples"]+0 < 3 || B["samples"]+0 < 3) {
        print "REFUSING to compare: fewer than 3 samples per arm (noise is unquantifiable)" > "/dev/stderr"
        exit 3
      }
      ma=A["fps_mean"]; mb=B["fps_mean"]; sa=A["fps_sd"]; sb=B["fps_sd"]
      na=A["samples"]+0; nb=B["samples"]+0
      se = sqrt(sa*sa/na + sb*sb/nb); d = mb - ma; ad = (d < 0 ? -d : d)
      printf "A.label=%s\nA.fps=%.3f +/- %.3f (n=%d)\n", A["label"], ma, sa, na
      printf "B.label=%s\nB.fps=%.3f +/- %.3f (n=%d)\n", B["label"], mb, sb, nb
      printf "delta_fps=%.3f\ndelta_pct=%.2f\nse_delta=%.3f\nthreshold_2se=%.3f\n",
             d, (ma > 0 ? 100.0*d/ma : 0), se, 2*se
      if (se <= 0) { print "INDETERMINATE (zero variance -- check the samples)" > "/dev/stderr"; exit 3 }
      print (ad > 2*se) ? "verdict=REAL" : "verdict=WITHIN_NOISE"
    }' "$a" "$b"
  local rc=$?
  set -e
  return $rc
}

# ------------------------------------------------------------------ dispatch

TITLE_ID=""; LOG=""; DRIVER_PATH=""; OUT=""; BEFORE_SUM=""
SAMPLES=3; SECONDS_PER_SAMPLE=20; MIN_SAMPLES=3; LAYER=""; LABEL="run"; TIMEOUT=120
CVARS=()

need_val() { [ -n "${2:-}" ] || die "$1 needs a value" "$EX_USAGE"; }

# The SUBCOMMAND comes first and options follow it, matching how the tool is
# documented ("bench-ab.sh assert-log --log ..."). Peel the command off, then
# parse the remaining arguments.
CMD="${1:-}"; [ $# -gt 0 ] && shift
case "$CMD" in
  preflight|device-info|snapshot-config|verify-config|wait-layer|sample|\
  assert-log|report|compare) ;;
  ""|--help|-h) usage; exit "$EX_OK";;
  *) die "unknown command: $CMD (try --help)" "$EX_USAGE";;
esac

while [ $# -gt 0 ]; do
  case "$1" in
    --title-id)     need_val "$1" "${2:-}"; TITLE_ID="$2"; shift 2;;
    --log)          need_val "$1" "${2:-}"; LOG="$2"; shift 2;;
    --driver-path)  need_val "$1" "${2:-}"; DRIVER_PATH="$2"; shift 2;;
    --expect|--expect-cvar) need_val "$1" "${2:-}"; CVARS+=("$2"); shift 2;;
    --out)          need_val "$1" "${2:-}"; OUT="$2"; shift 2;;
    --before)       need_val "$1" "${2:-}"; BEFORE_SUM="$2"; shift 2;;
    --samples)      need_val "$1" "${2:-}"; SAMPLES="$2"; shift 2;;
    --seconds)      need_val "$1" "${2:-}"; SECONDS_PER_SAMPLE="$2"; shift 2;;
    --min-samples)  need_val "$1" "${2:-}"; MIN_SAMPLES="$2"; shift 2;;
    --layer)        need_val "$1" "${2:-}"; LAYER="$2"; shift 2;;
    --label)        need_val "$1" "${2:-}"; LABEL="$2"; shift 2;;
    --timeout)      need_val "$1" "${2:-}"; TIMEOUT="$2"; shift 2;;
    --help|-h)      usage; exit "$EX_OK";;
    --) shift; break;;
    -*) die "unknown option: $1 (try --help)" "$EX_USAGE";;
    *) break;;   # first non-option belongs to the subcommand
  esac
done

case "$CMD" in
  preflight)       cmd_preflight "$@";;
  device-info)     cmd_device_info "$@";;
  snapshot-config) cmd_snapshot_config "$@";;
  verify-config)   cmd_verify_config "$@";;
  wait-layer)      cmd_wait_layer "$@";;
  sample)          cmd_sample "$@";;
  assert-log)      cmd_assert_log "$@";;
  report)          cmd_report "$@";;
  compare)         cmd_compare "$@";;
esac